# Generated by Django 3.2.16 on 2022-11-19 17:05

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hemo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='Nome')),
                ('latitude', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='Latitude')),
                ('longitude', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='Longitude')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
