# Generated by Django 3.2.16 on 2022-11-20 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hemo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hemo',
            old_name='latitude',
            new_name='geometria',
        ),
        migrations.RemoveField(
            model_name='hemo',
            name='longitude',
        ),
    ]
