# Generated by Django 3.2.16 on 2022-11-20 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hemo', '0003_rename_geometria_hemo_geometry'),
    ]

    operations = [
        migrations.AddField(
            model_name='hemo',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='hemo',
            name='uf',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Estado'),
        ),
    ]
